#!/bin/bash

Rscript -e 'desc::desc_set(Version="'"$1"'")'

git add -A
git commit -m "release $1"
git push

git checkout -b release-$1
git push --set-upstream origin release-$1

gh release create $1 --target=release-$1 --generate-notes
git checkout main
