# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(ggrrr)

# unit test start: .gg_tiny_theme ----

test_that(".gg_tiny_theme unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-ggplot-utils.R", line=166)
  # or navigate to topic with <F2>
  F2 = .gg_tiny_theme
  
  testthat::expect_no_error({
    
    ggplot2::ggplot(ggplot2::diamonds,
      ggplot2::aes(x=carat,y=price,color=color))+
      ggplot2::geom_point()+
      .gg_tiny_theme()
  })
})

# unit test end: .gg_tiny_theme ----
# unit test start: .gg_set_size_defaults ----

test_that(".gg_set_size_defaults unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-ggplot-utils.R", line=224)
  # or navigate to topic with <F2>
  F2 = .gg_set_size_defaults
  
  testthat::expect_no_error({
    
    .gg_set_size_defaults(lineSize = 0.25)
  })
})

# unit test end: .gg_set_size_defaults ----
# unit test start: .gg_substitute_fonts ----

test_that(".gg_substitute_fonts unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-ggplot-utils.R", line=303)
  # or navigate to topic with <F2>
  F2 = .gg_substitute_fonts
  
  
  testthat::expect_no_error({
    suppressWarnings(
     .gg_substitute_fonts(c("Roboto","Arial","Kings","Unmatched"))
    )
  })
})

# unit test end: .gg_substitute_fonts ----
# unit test start: .gg_fonts_missing ----

test_that(".gg_fonts_missing unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-ggplot-utils.R", line=360)
  # or navigate to topic with <F2>
  F2 = .gg_fonts_missing
  
  testthat::expect_no_error({
    
    .gg_fonts_missing("Arial")
    .gg_fonts_missing(c("Roboto","Kings","ASDASDAS"))
  })
})

# unit test end: .gg_fonts_missing ----
# unit test start: .gg_breaks_log1p ----

test_that(".gg_breaks_log1p unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-ggplot-utils.R", line=400)
  # or navigate to topic with <F2>
  F2 = .gg_breaks_log1p
  
  testthat::expect_no_error({
    
    ggplot2::ggplot(ggplot2::diamonds, ggplot2::aes(x=price))+
      ggplot2::geom_density()+
      ggplot2::scale_x_continuous(trans="log1p", breaks=.gg_breaks_log1p())
  })
})

# unit test end: .gg_breaks_log1p ----
# unit test start: .gg_transform_logit ----

test_that(".gg_transform_logit unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-ggplot-utils.R", line=425)
  # or navigate to topic with <F2>
  F2 = .gg_transform_logit
  
  testthat::expect_no_error({
    
    tibble::tibble(pvalue = c(0.001, 0.05, 0.1), fold_change = 1:3) %>%
     ggplot2::ggplot(ggplot2::aes(fold_change , pvalue)) +
     ggplot2::geom_point() +
     ggplot2::scale_y_continuous(transform= .gg_transform_logit())
  })
})

# unit test end: .gg_transform_logit ----
# unit test start: .gg_layer ----

test_that(".gg_layer unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-ggplot-utils.R", line=648)
  # or navigate to topic with <F2>
  F2 = .gg_layer
  
  
  # top level function contains `...` and `mapping` extensions points:
  myPlot = function(data, formula, ..., mapping = .gg_check_for_aes(...)) {
  xCol = rlang::as_quosure(rlang::f_lhs(formula), env = rlang::caller_env())
  yCol = rlang::as_quosure(rlang::f_rhs(formula), env = rlang::caller_env())
  ggplot2::ggplot(data) +
    .gg_layer(
      ggplot2::GeomPoint,
      data = data,
      mapping = ggplot2::aes(x = !!xCol, y = !!yCol, !!!mapping),
      ...,
      .default = list(size = 10)
    )
  }
  myPlot(iris, Sepal.Length~Sepal.Width, mapping=ggplot2::aes(colour=Species))
  myPlot(iris, Sepal.Length~Petal.Length, mapping=ggplot2::aes(colour=Species), shape="+", size=5)
  myPlot(mtcars, mpg~wt, mapping=ggplot2::aes(colour=as.factor(cyl), size=hp))
  # check we made it this far without calling expect_no_errors
  testthat::expect_equal(1,1)
})

# unit test end: .gg_layer ----
# unit test start: .gg_scale_y_logit ----

test_that(".gg_scale_y_logit unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-ggplot-utils.R", line=532)
  # or navigate to topic with <F2>
  F2 = .gg_scale_y_logit
  
  testthat::expect_no_error({
    
    tibble::tibble(pvalue = c(0.001, 0.05, 0.1), fold_change = 1:3) %>%
     ggplot2::ggplot(ggplot2::aes(fold_change , pvalue)) +
     ggplot2::geom_point() +
     .gg_scale_y_logit(n=8)
  })
})

# unit test end: .gg_scale_y_logit ----
# unit test start: .gg_scale_y_percent ----

test_that(".gg_scale_y_percent unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-ggplot-utils.R", line=571)
  # or navigate to topic with <F2>
  F2 = .gg_scale_y_percent
  
  testthat::expect_no_error({
    
    
    tibble::tibble(pvalue = c(0.001, 0.05, 0.1), fold_change = 1:3) %>%
     ggplot2::ggplot(ggplot2::aes(fold_change , pvalue)) +
     ggplot2::geom_point() +
     scale_y_percent()
  })
})

# unit test end: .gg_scale_y_percent ----
# end of unit tests ----
