# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(ggrrr)

# unit test start: .outputter ----

test_that(".outputter unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-file-output-utils.R", line=77)
  # or navigate to topic with <F2>
  F2 = .outputter
  
  # default appends date to filename:
  out <- .outputter(tempdir())
  tmp <- out("test.pdf")
  testthat::expect_match(
    tmp,
    "^.*/test-[0-9]{4}-[0-9]{2}-[0-9]{2}.pdf$"
  )
  
  # default appends date to filename:
  out2 <- .outputter(tempdir(), datedSubdirectory = TRUE)
  tmp2 <- out2("test.pdf")
  testthat::expect_match(
    tmp2,
    "^.*/[0-9]{4}-[0-9]{2}-[0-9]{2}/test.pdf$"
  )
})

# unit test end: .outputter ----
# unit test start: .this_script ----

test_that(".this_script unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-file-output-utils.R", line=133)
  # or navigate to topic with <F2>
  F2 = .this_script
  
  testthat::expect_no_error(withCallingHandlers(
    {
      .this_script()
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))
})

# unit test end: .this_script ----
# unit test start: .locate_project ----

test_that(".locate_project unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-file-output-utils.R", line=183)
  # or navigate to topic with <F2>
  F2 = .locate_project
  
  testthat::expect_no_error(withCallingHandlers(
    {
      .locate_project()
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))
})

# unit test end: .locate_project ----
# unit test start: .here ----

test_that(".here unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-file-output-utils.R", line=264)
  # or navigate to topic with <F2>
  F2 = .here
  
  testthat::expect_no_error(withCallingHandlers(
    {
      .here("vignettes")
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))
})

# unit test end: .here ----
# unit test start: .find_chrome ----

test_that(".find_chrome unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-file-output-utils.R", line=288)
  # or navigate to topic with <F2>
  F2 = .find_chrome
  
  testthat::expect_no_error(withCallingHandlers(
    {
      # no test possible: this will be skipped
      try(.find_chrome())
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))
})

# unit test end: .find_chrome ----
# unit test start: .print_svg_with_chrome ----

test_that(".print_svg_with_chrome unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-file-output-utils.R", line=352)
  # or navigate to topic with <F2>
  F2 = .print_svg_with_chrome
  
  tryCatch(.find_chrome(), error = function(e) testthat::skip())
  
  plot <- ggplot2::ggplot(
    ggplot2::diamonds,
    ggplot2::aes(x = carat, y = price, color = color)
  ) +
    ggplot2::geom_point() +
    ggplot2::annotate(
      "label",
      x = 2,
      y = 10000,
      label = "Hello \u2014 world",
      family = "Kings"
    ) +
    ggplot2::labs(tag = "A") +
    ggplot2::xlab("Carat\u2082") +
    ggplot2::ylab("price\u2265")
  
  res <- plot %>% .gg_save_as(filename = tempfile(), formats = c("svg"))
  
  # res_content = readr::read_file_raw(res$svg)
  # testthat::expect_equal(rlang::hash(res_content), "99e7c62601699705bbb13dacf621caca")
  
  testthat::expect_no_error({
    .print_svg_with_chrome(res$svg)
  })
  
  # exact binary copy may depend on versions of chrome etc:
})

# unit test end: .print_svg_with_chrome ----
# unit test start: .print_html_with_chrome ----

test_that(".print_html_with_chrome unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-file-output-utils.R", line=451)
  # or navigate to topic with <F2>
  F2 = .print_html_with_chrome
  
  tryCatch(.find_chrome(), error = function(e) testthat::skip())
  
  hux <- iris %>%
    huxtable::as_hux() %>%
    huxtable::theme_mondrian(font = "Roboto")
  html <- hux %>% huxtable::to_html()
  
  testthat::expect_no_error({
    tmp <- .print_html_with_chrome(
      html,
      maxWidth = 5,
      maxHeight = std_size$A4$height
    )
  })
  # browseURL(tmp)
  
  # exact binary copy may depend on versions of chrome etc:
  
  
  # The resulting pdf has fonts embedded & is multipage.
})

# unit test end: .print_html_with_chrome ----
# unit test start: .convert_pdf_to_pngs ----

test_that(".convert_pdf_to_pngs unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-file-output-utils.R", line=542)
  # or navigate to topic with <F2>
  F2 = .convert_pdf_to_pngs
  
  testthat::expect_no_error(withCallingHandlers(
    {
      hux <- iris %>%
        huxtable::as_hux() %>%
        huxtable::theme_mondrian(font = "Arial")
      html <- hux %>% huxtable::to_html()
      tmp <- .print_html_with_chrome(
        html,
        maxWidth = std_size$A4$width,
        maxHeight = std_size$A4$height
      )
      pngs <- .convert_pdf_to_pngs(tmp)
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))
})

# unit test end: .convert_pdf_to_pngs ----
# unit test start: .gg_save_as ----

test_that(".gg_save_as unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-file-output-utils.R", line=698)
  # or navigate to topic with <F2>
  F2 = .gg_save_as
  
  testthat::expect_no_error(withCallingHandlers(
    {
      .gg_pedantic(fontSize = 6)
      p <- ggplot2::ggplot(mtcars, ggplot2::aes(mpg, wt, colour = as.factor(cyl))) +
        ggplot2::geom_point()
      # p %>% .gg_save_as(filename="~/tmp/plot_example",maxWidth=4,maxHeight=4)
      p %>% .gg_save_as(filename = tempfile(), maxWidth = 2, maxHeight = 1.5)
  
      plot <- ggplot2::ggplot(
        ggplot2::diamonds,
        ggplot2::aes(x = carat, y = price, color = color)
      ) +
        ggplot2::geom_point() +
        ggplot2::annotate(
          "label",
          x = 2,
          y = 10000,
          label = "Hello \u2014 world",
          family = "Kings"
        ) +
        ggplot2::labs(tag = "A") +
        ggplot2::xlab("Carat\u2082") +
        ggplot2::ylab("price\u2265")
  
      # plot %>% .gg_save_as(filename="~/tmp/plot_example_2")
      res <- plot %>% .gg_save_as(filename = tempfile(), formats = c("png", "eps"))
      as.character(res)
      res
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))
})

# unit test end: .gg_save_as ----
# unit test start: .hux_save_as ----

test_that(".hux_save_as unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-file-output-utils.R", line=1016)
  # or navigate to topic with <F2>
  F2 = .hux_save_as
  
  testthat::expect_no_error(withCallingHandlers(
    {
      hux <- iris %>%
        huxtable::as_hux() %>%
        huxtable::theme_mondrian(font = "Roboto")
      out <- .hux_save_as(hux, tempfile())
      # browseURL(out$html)
  
      out2 <- .hux_save_as(hux, tempfile(), formats = c("pdf", "png"))
      as.character(out2)
      # The resulting pdf has fonts embedded & is multipage.
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))
})

# unit test end: .hux_save_as ----
# end of unit tests ----
