# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(ggrrr)

# unit test start: .cached ----

test_that(".cached unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-cache.R", line=57)
  # or navigate to topic with <F2>
  F2 = .cached
  
  
  
  # we use `rnorm` here to prove that the cache is working but in reality
  # you would normally only use something deterministic in `.expr`:
  x = 100
  tmp = .cached(stats::rnorm(x), x)
  tmp2 = .cached(stats::rnorm(x), x)
  testthat::expect_equal(tmp, tmp2)
  
  x = 200
  tmp3 = .cached(stats::rnorm(x), x)
  testthat::expect_equal(x, length(tmp3))
  
})

# unit test end: .cached ----
# end of unit tests ----
