# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(ggrrr)

# unit test start: .pmixnorm ----

test_that(".pmixnorm unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-mixture-distributions.R", line=39)
  # or navigate to topic with <F2>
  F2 = .pmixnorm
  
  testthat::expect_no_error({
    
    .pmixnorm(q=c(2,20), means=c(10,13,14), sds=c(1,1,2), weights=c(2,2,3))
  })
})

# unit test end: .pmixnorm ----
# unit test start: .qmixnorm ----

test_that(".qmixnorm unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-mixture-distributions.R", line=59)
  # or navigate to topic with <F2>
  F2 = .qmixnorm
  
  testthat::expect_no_error({
    
    .qmixnorm(p=c(0.025,0.5,0.975), means=c(10,13,14), sds=c(1,1,2))
  })
})

# unit test end: .qmixnorm ----
# unit test start: .pmixlnorm ----

test_that(".pmixlnorm unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-mixture-distributions.R", line=88)
  # or navigate to topic with <F2>
  F2 = .pmixlnorm
  
  testthat::expect_no_error({
    
    .pmixlnorm(q=c(2,20), meanlogs=c(1.0,1.3,1.4), sdlogs=c(1,1,2), weights=c(2,2,3))
  })
})

# unit test end: .pmixlnorm ----
# unit test start: .qmixlnorm ----

test_that(".qmixlnorm unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-mixture-distributions.R", line=108)
  # or navigate to topic with <F2>
  F2 = .qmixlnorm
  
  testthat::expect_no_error({
    
    .qmixlnorm(p=c(0.025,0.5,0.975), meanlogs=c(1,1.3,1.4), sdlogs=c(0.1,0.1,0.2))
    .qmixlnorm(p=c(0.025,0.5,0.975), meanlogs=c(1,1.3,1.4), sdlogs=c(0.1,0.1,0.2), method="samples")
    .qmixlnorm(p=c(0.025,0.5,0.975), meanlogs=c(1,1.3,1.4), sdlogs=c(0.1,0.1,0.2), method="moments")
    
  })
})

# unit test end: .qmixlnorm ----
# unit test start: .pmixgamma ----

test_that(".pmixgamma unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-mixture-distributions.R", line=141)
  # or navigate to topic with <F2>
  F2 = .pmixgamma
  
  testthat::expect_no_error({
    
    .pmixgamma(q=c(2,20), shapes=c(10,13,14), rates=c(1,1,1), weights=c(2,2,3))
  })
})

# unit test end: .pmixgamma ----
# unit test start: .qmixgamma ----

test_that(".qmixgamma unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-mixture-distributions.R", line=161)
  # or navigate to topic with <F2>
  F2 = .qmixgamma
  
  testthat::expect_no_error({
    
    .qmixgamma(p=c(0.025,0.5,0.975), shapes=c(10,13,14), rates=c(1,1,2), method="moments")
    .qmixgamma(p=c(0.025,0.5,0.975), shapes=c(10,13,14), rates=c(1,1,2), method="exact")
  })
})

# unit test end: .qmixgamma ----
# unit test start: .pmixbeta ----

test_that(".pmixbeta unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-mixture-distributions.R", line=192)
  # or navigate to topic with <F2>
  F2 = .pmixbeta
  
  testthat::expect_no_error({
    
    .pmixbeta(q=c(2,20), alphas=c(10,13,14), betas=c(1,1,1), weights=c(2,2,3))
  })
})

# unit test end: .pmixbeta ----
# unit test start: .qmixbeta ----

test_that(".qmixbeta unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-mixture-distributions.R", line=212)
  # or navigate to topic with <F2>
  F2 = .qmixbeta
  
  testthat::expect_no_error({
    
    .qmixbeta(p=c(0.025,0.5,0.975), alphas=c(10,13,14), betas=c(1,1,2))
    .qmixbeta(p=c(0.025,0.5,0.975), alphas=c(10,13,14), betas=c(1,1,2), method="moments")
  })
})

# unit test end: .qmixbeta ----
# unit test start: .pmix ----

test_that(".pmix unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-mixture-distributions.R", line=257)
  # or navigate to topic with <F2>
  F2 = .pmix
  
  testthat::expect_no_error({
    
    
    # a single mixture with vectorised input:
    .pmix("norm", seq(-5,5,1), param1=c(-1,0,1), param2=c(1,1,1))
    
    # `.pmix` does not support a list of lists as an input
    # i.e. it is vectorised over the input x, but each mixture distribution
    # is specified individually with a vector `param1` and `param2`, and it is
    # not vectorised on `param1` and `param2`. # This is a bit different to pnorm
    # for example # where multiple `mean`/`sd` values are supported and vectorised as well
    # as the x input.
    
    .pmix("norm", c(3,5,10), param1=c(6,7,8,9), param2=3)
    
  })
})

# unit test end: .pmix ----
# end of unit tests ----
