# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(ggrrr)

# unit test start: .hux_substitute_fonts ----

test_that(".hux_substitute_fonts unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-huxtable-utils.R", line=29)
  # or navigate to topic with <F2>
  F2 = .hux_substitute_fonts
  
  testthat::expect_no_error(withCallingHandlers(
    {
      .hux_substitute_fonts(c("Roboto", "Arial", "Kings", "Unmatched"))
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))
})

# unit test end: .hux_substitute_fonts ----
# unit test start: .hux_default_layout ----

test_that(".hux_default_layout unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-huxtable-utils.R", line=96)
  # or navigate to topic with <F2>
  F2 = .hux_default_layout
  
  testthat::expect_no_error(withCallingHandlers(
    {
      hux <- iris %>% .hux_default_layout()
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))
})

# unit test end: .hux_default_layout ----
# end of unit tests ----
