# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(ggrrr)

# unit test start: .hux_substitute_fonts ----

test_that(".hux_substitute_fonts unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-huxtable-utils.R", line=29)
  # or navigate to topic with <F2>
  F2 = .hux_substitute_fonts
  
  
  tmp = suppressWarnings(
    .hux_substitute_fonts(c("Roboto","Arial","Kings","Unmatched"))
  )
  testthat::expect_equal(tmp[[1]],"Roboto")
})

# unit test end: .hux_substitute_fonts ----
# unit test start: .hux_default_layout ----

test_that(".hux_default_layout unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-huxtable-utils.R", line=99)
  # or navigate to topic with <F2>
  F2 = .hux_default_layout
  
  
  hux = iris %>% .hux_default_layout()
  testthat::expect_equal(rlang::hash(hux), "8dd7e558ac7d0e8d27b2f815f6065fe1")
})

# unit test end: .hux_default_layout ----
# end of unit tests ----
