# Generated by doctest: do not edit by hand
# Please edit file in R/standalone-singleton.R

test_that("Doctest: .singleton", {
  # Created from @doctest for `.singleton`
  # Source file: R/standalone-singleton.R
  # Source line: 25
  fixed_rnorm = .singleton(rnorm(10))
  a = fixed_rnorm()
  b = fixed_rnorm()
  expect_equal(b, a)
})

