# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(ggrrr)

# unit test start: .singleton ----

test_that(".singleton unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-singleton.R", line=25)
  # or navigate to topic with <F2>
  F2 = .singleton
  
  
  fixed_rnorm = .singleton(rnorm(10))
  a = fixed_rnorm()
  b = fixed_rnorm()
  testthat::expect_equal(a,b)
})

# unit test end: .singleton ----
# end of unit tests ----
