# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(ggrrr)

# unit test start: .memoise ----

test_that(".memoise unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/standalone-memoise.R", line=34)
  # or navigate to topic with <F2>
  F2 = .memoise
  
  
  lmmem = .memoise(stats::lm)
  lmmem2 = .memoise(stats::lm)
  testthat::expect_identical(lmmem, lmmem2)
  
  result1 = lmmem(Petal.Width ~ Petal.Length, iris)
  result2 = lmmem2(Petal.Width ~ Petal.Length, iris)
  
  # attr(result1,"cache")
  # attr(result2,"cache")
  
  testthat::expect_identical(result1,result2)
  
  # memoise a purrr style lambda:
  plus = .memoise(~ .x + .y)
  testthat::expect_equal(plus(2,2),4)
  
  
  tmp = .memoise(function(x,y) {z})
  testthat::expect_error(tmp(1,2))
})

# unit test end: .memoise ----
# end of unit tests ----
